### ISSUE TITLE
Create base React app

### ISSUE THREAD

**Issue by kairuihuang** [software-students-fall2021/rokietnica-logistical-app#5]
**Task**: Run create-react-app to generate app skeleton for React frontend
**Estimation of Effort**: 1-2 units

**Acceptance Criteria**
- [x] Files from create-react-app are completed
- [x] Any setup information is filled in, and any other work needed for setup
- [x] The app can be built and run with no *project* content
- [x] Others can write code and have their changes be reflected when running the app

Note: I kept most of the placeholder content from `create-react-app` for reference. With `react-router-dom`, you should be able to generate JSX for different views from our wireframes.
